export const dojo = {
    "de": [
        "Unser Dojo",
        "Wir freuen uns darauf, Sie in unserer Karate-Sparte begrüßen zu dürfen. Unsere Sporthalle befindet sich in einer günstigen Lage und ist leicht zu erreichen. Bitte zögern Sie nicht uns zu kontaktieren, falls Sie Hilfe bei der Anfahrt benötigen.",
        "Turn- u. Festhalle, Rappengasse, Rheinzabern (GER)",
    ],
    "en": [
        "Our Dojo",
        "We look forward to welcoming you to our karate division. Our gym is conveniently located and easy to get to. Please do not hesitate to contact us if you need any help with directions.",
        "Jockgrimer Str. 100, 76764 Rheinzabern (GER)",
    ],
    "ja": [
        "私たちの道場",
        "空手部へのご参加をお待ちしております。 私たちのスポーツホールは、便利な場所にあり、簡単にアクセスできます。案内が必要な場合は、ご遠慮なくお問い合わせください。",
        "Jockgrimer Str. 100, 76764 Rheinzabern (GER)",
    ],
    "un": [
        "A mi Dojo-nk",
        "Szeretettel várjuk Önt karate részlegünkben. Edzőtermünk kényelmes helyen található és könnyen megközelíthető. Kérjük, ne habozzon kapcsolatba lépni velünk, ha segítségre van szüksége az útbaigazítással kapcsolatban.",
        "Jockgrimer Str. 100, 76764 Rheinzabern (GER)",
    ],
    "uk": [
        "Наше додзьо",
        "Ми будемо раді вітати вас у нашій секції карате. Наш тренажерний зал зручно розташований і до нього легко дістатися. Будь ласка, не соромтеся звертатися до нас, якщо вам потрібна будь-яка допомога з інструкціями",
        "Jockgrimer Str. 100, 76764 Rheinzabern (GER)",
    ]
}

export const times = {
    "de": [
        "Trainingszeiten",
        "Wir haben zwei Hallen in denen wir Trainieren dürfen, beide befinden sich auf dem Schulcampus der IGS Rheinzabern. Die eine Halle wird als VG Jockgrim, die andere als OG Rheinzabern bezeichnet. Beide Halle liegen direkt nebeneinander, der Eingang befindet sich ca. 10 Meter voneinander entfernt ist. Falls sie also Interesse an einer Karate- oder Selbstverteidigungsklasse haben, können sie gerne nach Anmeldung zu den Hallen kommen. Dort werden sie von einem unserer Trainer begrüßt.",
        "Kinder- und Anfänger Training",
        "Das Kindertraining im findet regelmäßig an zwei Terminen pro Woche statt. Einer der Termine ist Dienstags von 18:00 bis 19:00 Uhr, während der andere Freitags von 18:00 bis 19:00 Uhr angeboten wird. Ebenfalls sind auch Erwachsene Anfänger herzlich eingeladen, an diesen Trainingseinheiten teilzunehmen. Dies ermöglicht es ihnen, gemeinsam mit den Kindern die Grundlagen des Karate zu erlernen und ihre Fähigkeiten in einer freundlichen und unterstützenden Umgebung zu entwickeln..",
        "Dienstag",
        "Erwachsenen- und Fortgeschrittenen Training",
        "Unsere Erwachsenen und Fortgeschrittenen Mitglieder im Karateverein Kenkyo trainieren jeden Dienstag von 19:00 Uhr bis 21:00 Uhr. Zusätzlich findet das Training auch Freitags zur gleichen Uhrzeit statt. Beide Trainingseinheiten werden in derselben Sporthalle abgehalten, um den Teilnehmern eine vertraute und beständige Umgebung zu bieten. Durch diese regelmäßigen Trainings haben die Erwachsenen und Fortgeschrittenen Karatekas die Möglichkeit, ihre Fertigkeiten kontinuierlich zu verbessern und sich auf Wettkämpfe oder Prüfungen vorzubereiten. Der Verein legt Wert darauf, eine anspruchsvolle und zugleich fördernde Atmosphäre zu schaffen, die den Fortschritt und die persönliche Entwicklung jedes Mitglieds unterstützt.",
        "Schwarzgurt Training",
        "Freitag",
        "Für unsere Schwarzgurt-Träger und auch Schwarzgurt Anwärter bieten wir ein exklusives Spezialtraining an, das auf ihre individuellen Bedürfnisse und Fähigkeiten zugeschnitten ist. Dieses hochwertige Training richtet sich an fortgeschrittene Karatekas, die ihr Können auf höchstem Niveau weiterentwickeln möchten. Durch gezielte Übungen und persönliche Betreuung durch erfahrene Trainer erhalten die Teilnehmer die Möglichkeit, ihre Techniken zu verfeinern und ihre mentale Stärke zu stärken. Das Spezialtraining unterstützt die Schwarzgurte dabei, ihr volles Potenzial auszuschöpfen und ihre Karriere im Karatesport voranzubringen. Der Karateverein Kenkyo beweist damit einmal mehr sein Engagement für die kontinuierliche Weiterentwicklung seiner Mitglieder und den Erhalt der hohen Qualität in der Ausbildung.",
        "Altersvorsorge Training",
        "Samstag",
        "Wir bieten jeden Samstag von 9:00 bis 11:30 Uhr ein spezielles Training für ältere und verletzte Menschen an. Dieses Training zielt darauf ab, die körperliche Fitness und Beweglichkeit der Teilnehmer auf sanfte Weise zu verbessern. Karate hilft diesen Menschen, ihre Balance und Koordination zu stärken, was Stürze und Verletzungen vorbeugen kann. Durch das Erlernen von Selbstverteidigungstechniken gewinnen sie zudem an Selbstvertrauen und Sicherheit im Alltag. Das individuell angepasste Karatetraining fördert somit die Lebensqualität der betroffenen Personen und trägt zur Stärkung ihrer körperlichen und geistigen Gesundheit bei.",
        "Speziall Training",
        "Ebenfalls bieten wir jeden Samstag von 9:00 bis 11:30 Uhr in der Halle ein spezielles Training für Wettkampf- und Prüfungsvorbereitungen für fortgeschrittene Karatekas an. Diese zusätzlichen Trainingseinheiten sind jedoch nur nach vorheriger Absprache mit den Trainern möglich.",
        "Ohne Ende",
        "Donnerstag"
    ],
    "en": [
        "Training Times",
        "We have two halls in which we are allowed to train, both are located on the school campus of IGS Rheinzabern. One hall is called VG Jockgrim, the other OG Rheinzabern. Both halls are right next to each other, the entrance is about 10 meters away from each other. So if you are interested in a karate or self-defense class, you are welcome to come to the halls after registration. There they will be welcomed by one of our trainers.",
        "Children and beginners training",
        "Children's training in is held regularly on two dates per week. One of the dates is Tuesdays from 18:00 to 19:00, while the other is offered on Fridays from 18:00 to 19:00. Likewise, adult beginners are also welcome to participate in these training sessions. This allows them to learn the basics of karate along with the children and develop their skills in a friendly and supportive environment....",
        "Tuesday",
        "Adult and Advanced Training",
        "Our adult and advanced members at Kenkyo Karate Club train every Tuesday from 7:00 pm to 9:00 pm. In addition, training is also held on Fridays at the same time. Both training sessions are held in the same gym to provide participants with a familiar and consistent environment. Through these regular training sessions, the adult and advanced karatekas have the opportunity to continuously improve their skills and prepare for competitions or exams. The club makes it a point to provide a challenging yet nurturing atmosphere that supports the progress and personal development of each member.",
        "Black Belt Training",
        "Friday",
        "For our black belt wearers and also black belt aspirants, we offer an exclusive special training tailored to their individual needs and abilities. This high-quality training is aimed at advanced karatekas who want to further develop their skills at the highest level. Through targeted exercises and personal attention from experienced trainers, participants are given the opportunity to refine their techniques and build mental strength. Specialized training helps black belts reach their full potential and advance their careers in karate. Once again, Kenkyo Karate Club demonstrates its commitment to the continued development of its members and the maintenance of high quality training.",
        "Retirement Training",
        "Saturday",
        "We offer a special training for elderly and injured people every Saturday from 9:00 to 11:30 am in the hall. This training aims to improve the physical fitness and mobility of the participants in a gentle way. Karate helps these people to strengthen their balance and coordination, which can prevent falls and injuries. By learning self-defense techniques, they also gain confidence and security in everyday life. Thus, the customized karate training promotes the quality of life of the people concerned and contributes to strengthening their physical and mental health.",
        "Special Training",
        "Likewise, we offer special training for competition and exam preparation for advanced karatekas every Saturday from 9:00 to 11:30 am in the hall. However, these additional training sessions are only available by prior arrangement with the coaches.",
        "No End",
        "Thursday"
    ],
    "ja": [
        "トレーニング時間 ",
        "の校内にある2つのホールでトレーニングを行うことが許されています。一つはVG Jockgrim、もう一つはOG Rheinzabernと呼ばれるホールです。両会場とも入り口は10メートルほど離れていて、すぐ隣同士です。ですから、空手や護身術のクラスに興味がある方は、受付を済ませた後、ぜひホールに来てください。そこで私たちのトレーナーが出迎えてくれるでしょう」、",
        "子供と初心者のためのトレーニング",
        "の子供たちのトレーニングは、週に2回の日程で定期的に行われます。一つは火曜日の18:00～19:00、もう一つは金曜日の18:00～19:00に開催されます。このセッションには、大人の初心者の方も参加することができます。これにより、子供たちと一緒に空手の基本を学び、フレンドリーで協力的な環境の中で技術を向上させることができます...",
        "火曜日",
        "大人・上級者向け稽古 を開催します、,",
        "剣幸空手クラブの大人・上級会員は、毎週火曜日の19時から21時まで稽古をしています。また、金曜日も同じ時間帯に稽古が行われています。どちらの稽古も同じジムで行われ、参加者が慣れ親しみ、一貫した環境を提供できるようにしています。これらの定期的なトレーニングセッションを通じて、成人および上級空手家は、継続的に技術を向上させ、大会や試験に向けて準備する機会を得ています。クラブは、メンバー一人ひとりの上達と個人的な成長をサポートするために、挑戦的でありながら育成的な雰囲気を作り出すことを大切にしています。",
        "黒帯のトレーニング",
        "金曜日 ",
        "黒帯着用者 と 黒帯志望者 のために、個々のニーズと能力に合わせた特別なトレーニングを提供します。この高品質なトレーニングは、最高レベルのスキルをさらに向上させたい上級空手家を対象としています。経験豊富なトレーナーによる個人的な配慮と的を絞った練習により、参加者は技を磨き、精神的な強さを身につける機会を得ます。この特別なトレーニングは、黒帯がその潜在能力を最大限に発揮し、空手界でキャリアを積むのに役立つものです。今回も剣友会は、会員の継続的な発展と質の高いトレーニングの維持に尽力していることを証明しました。",
        "引退後のトレーニング",
        "土曜日 ",
        "同様に、毎週土曜日の午前9時から11時30分まで、地元ラインツァベルンの自治体のホールで、上級カラテカーのための大会や試験準備のための特別トレーニングを実施しています。ただし、これらの追加トレーニングは、トレーナーとの事前の取り決めによってのみ可能です。",
        "特別なトレーニング",
        "同様に、毎週土曜日の9:00から11:30まで、上級カラテカーのための大会や試験準備のための特別トレーニングをホールで行っています。ただし、これらの追加トレーニングは、コーチとの事前の打ち合わせによってのみ可能です。とあります、",
        "終わりなく ",
        "木曜日"
    ],
    "un": [
        "Képzési idők",
        "Két csarnokunk van, ahol edzhetünk, mindkettő az iskolai campusán található. Az egyik csarnok neve VG Jockgrim, a másik OG Rheinzabern. Mindkét csarnok közvetlenül egymás mellett van, a bejárat körülbelül 10 méterre van egymástól. Tehát ha érdekel egy karate vagy önvédelmi óra, akkor regisztráció után szívesen látunk a termekben. Ott az egyik edzőnk fogja őket fogadni.",
        "Gyermek és kezdő edzések,",
        "Gyermek edzés in rendszeresen heti két időpontban kerül megrendezésre. Az egyik időpont keddenként 18:00 és 19:00 óra között, míg a másik péntekenként 18:00 és 19:00 óra között kerül megrendezésre. Ezekre a foglalkozásokra felnőtt kezdőket is szívesen látunk. Így ők is csatlakozhatnak a gyerekekhez, hogy barátságos és támogató környezetben tanulják meg a karate alapjait és fejlesszék képességeiket....",
        "Kedd,",
        "Felnőtt és haladó edzés",
        "A Kenkyo Karate Klub felnőtt és haladó tagjaink minden kedden 19 órától 21 óráig edzenek. Ezen kívül péntekenként ugyanebben az időpontban is zajlik edzés. Mindkét edzés ugyanabban az edzőteremben zajlik, hogy a résztvevők számára családias és egységes környezetet biztosítsunk. Ezeken a rendszeres edzéseken keresztül a felnőtt és haladó karatésoknak lehetőségük van arra, hogy folyamatosan fejlesszék képességeiket és felkészüljenek a versenyekre vagy vizsgákra. A klub fontosnak tartja, hogy olyan kihívást jelentő, de mégis gondoskodó légkört teremtsen, amely támogatja minden egyes tag fejlődését és személyes fejlődését.",
        "Fekete öves képzés,",
        "Péntek",
        "Fekete öv viselőink és a fekete övre törekvők számára exkluzív, speciális, az egyéni igényekre és képességekre szabott képzést kínálunk. Ez a magas színvonalú képzés a haladó karatésoknak szól, akik a legmagasabb szinten szeretnék továbbfejleszteni képességeiket. Célzott gyakorlatok és tapasztalt edzők személyes figyelme révén a résztvevők lehetőséget kapnak technikáik finomítására és mentális erejük fejlesztésére. A speciális képzés segít a fekete öveseknek, hogy teljes mértékben kiaknázzák a bennük rejlő lehetőségeket és előrébb lépjenek karate karrierjükben. A Kenkyo Karate Klub ismét bizonyítja elkötelezettségét tagjai folyamatos fejlődése és a magas színvonalú képzés fenntartása iránt.",
        "Nyugdíjas edzés",
        "Szombat",
        "Hasonlóképpen, minden szombaton 9:00 és 11:30 között a helyi önkormányzat Rheinzabern termében speciális verseny- és vizsgafelkészítő edzéseket kínálunk haladó karatésoknak. Ezek a kiegészítő edzések azonban csak az edzőkkel való előzetes egyeztetés alapján lehetségesek",
        "Speciális képzés",
        "Hasonlóképpen, minden szombaton 9:00 és 11:30 között a teremben speciális verseny- és vizsgafelkészítő edzéseket tartunk haladó karatésoknak. Ezek a kiegészítő edzések azonban csak az edzőkkel való előzetes egyeztetés alapján lehetségesek.",
        "Vég nélkül",
        "Csütörtök"
    ],
    "uk": [
        "Час тренувань",
        "У нас є два зали, в яких нам дозволено тренуватися, обидва знаходяться на території школи IGS Rheinzabern. Один зал називається VG Jockgrim, інший - OG Rheinzabern. Обидва зали знаходяться поруч один з одним, вхід до них знаходиться на відстані близько 10 метрів один від одного. Тож якщо ви зацікавлені у заняттях з карате чи самооборони, то після реєстрації можете зайти до залів. Там їх зустріне один з наших тренерів",
        "Дитячі тренування та тренування для початківців",
        "Дитячі тренування проходять регулярно два рази на тиждень. Одна з дат - щовівторка з 18:00 до 19:00, інша - щоп'ятниці з 18:00 до 19:00. Дорослі початківці також можуть відвідувати ці заняття. Це дозволяє їм приєднатися до дітей у вивченні основ карате та розвитку своїх навичок у дружньому та сприятливому середовищі....",
        "Вівторок",
        "Дорослі та просунуті тренування",
        "Наші дорослі та просунуті члени клубу карате Кенкіо тренуються щовівторка з 19:00 до 21:00. Крім того, тренування також проходять по п'ятницях в той же час. Обидва тренування проходять в одному і тому ж залі, щоб забезпечити учасникам знайому і стабільну обстановку. Завдяки цим регулярним тренуванням дорослі та досвідчені каратисти мають можливість постійно вдосконалювати свої навички та готуватися до змагань чи іспитів. Клуб ставить собі за мету створити складну, але в той же час сприятливу атмосферу, яка підтримує прогрес і особистий розвиток кожного члена клубу",
        "Тренування на чорний пояс",
        "П'ятниця",
        "Для наших власників чорних поясів, а також абітурієнтів на отримання чорного поясу, ми пропонуємо ексклюзивні спеціальні тренування, адаптовані до їхніх індивідуальних потреб та здібностей. Цей високоякісний тренінг спрямований на просунутих каратистів, які хочуть продовжувати розвивати свої навички на найвищому рівні. Завдяки цілеспрямованим вправам та персональній увазі досвідчених тренерів, учасники отримують можливість вдосконалити свою техніку та зміцнити психологічну силу. Спеціальна підготовка допомагає чорним поясам повністю реалізувати свій потенціал та просунутись у кар'єрі каратиста. В черговий раз Кенкьо Карате Клуб демонструє свою прихильність до постійного розвитку своїх членів та підтримання високої якості тренувань",
        "Тренування для пенсіонерів",
        "Субота",
        "Крім того, ми пропонуємо спеціальні тренування для підготовки до змагань та іспитів для каратистів високого рівня щосуботи з 9:00 до 11:30 у залі місцевого муніципалітету Райнзаберна. Однак ці додаткові тренування можливі лише за попередньою домовленістю з тренерами",
        "Спеціальні тренування",
        "Також ми пропонуємо спеціальні тренування для підготовки до змагань та іспитів для просунутих каратистів щосуботи з 9:00 до 11:30 ранку в залі. Однак ці додаткові тренування можливі лише за попередньою домовленістю з тренерами",
        "Без кінця",
        "Четвер"
    ]
}

export const offers = {
    "de": [
        "Angebote",
        "Im folgenden sind unsere 5 Mitgliedschaften aufgeführt. Solltest du Interesse haben, dann kannst du gerne ein Probetraining vereinbaren oder eine Kurzzeitmitgliedschaft buchen. Alle weiteren Informationen erhaltest du nach Kontaktaufnahme bei uns",
        "Normale Mitgliedschaft",
        "Mit 65€ jedes Halbe Jahr erhaltest du unsere Normale Mitgliedschaft beinhaltet die Teilnahme an allen Trainingseinheiten welche von uns bereit gestellt werden. Dies kannst du als Volljährige Person erwerben, es kann Monatlich gekündigt werden, ansonsten wird deine Mitgliedschaft automatisch verlängert.",
        "Das Familien Angebot",
        "Unser Familien Angebot zielt auf Sportbegeisterte Familien ab. Nicht nur du, sondern auch dein Kind beziehungsweise deine Partner/-in kann zu einem besseren Angebot mittrainieren. Dies kann als Volljährige Person erworben werden, es kann Monatlich gekündigt werden, ansonsten wird deine Mitgliedschaft automatisch verlängert. Ab dem 2. Mitglied, Zahlt der Höchsteingestufte normal.",
        "Speziell für Schüler, Studenten und Azubis",
        "Mit 55€ jedes Halbe Jahr erhalten unsere Schüler, Studenten und Azubis eine günstigere Normale Mitgliedschaft. Dies beinhaltet die Teilnahme an allen Trainingseinheiten welche von uns bereit gestellt werden. Dies kannst du als Volljährige Person erwerben, es kann Monatlich gekündigt werden, ansonsten wird deine Mitgliedschaft automatisch verlängert.",
        "Unser Kinderangebot",
        "Auch unsere Kinder werden im Vergleich zu einer Normalen Mitgliedschaft begünstigt, mit 45€ jedes Halbe Jahr erhalten Sie eine günstigere Normale Mitgliedschaft. Dies beinhaltet die Teilnahme an allen Trainingseinheiten welche von uns bereit gestellt werden. Dies kannst du als Volljährige Person erwerben, es kann Monatlich gekündigt werden, ansonsten wird deine Mitgliedschaft automatisch verlängert.",
        "Kurzzeitmitgliedschaft",
        "Als einer der wenigen Kampfsport Verein / Schulen bietet Kenkyo erstmals Kurzzeitmitgliedschaften an. Für einmalig 30€ kannst du innerhalb 3 Monate so oft Trainieren kommen wie du möchtest. Danach wirst du automatisch gekündigt und kannst keine weitere Kurzzeitmitgliedschaft buchen. Hast du also weiterhin Interesse, stehen die obige Angebote offen.",
        "Monate",
        "Zu den unten genannten Kosten, kommen ebenfalls 20€ Verwaltungsaufwand.",
    ],
    "en": [
        "Our Offers to You",
        " Below are our 5 memberships. If you are interested, you are welcome to arrange a trial training or book a short-term membership. You will receive all further information after contacting us",
        "Normal Membership",
        "With 65€ every half year you get our normal membership which includes the participation in all training sessions which are provided by us. You can buy this as an adult person, it can be cancelled monthly, otherwise your membership will be automatically renewed",
        "The Family Offer",
        "Our family offer is aimed at sports enthusiastic families. Not only you, but also your child or partner can train at a better offer. This can be purchased as an adult person, it can be canceled monthly, otherwise your membership will be automatically renewed. From the 2nd member, pays the Höchsteingestufte normal.",
        "Especially for pupils, students and trainees",
        "With 55€ every half year, our pupils, students and trainees receive a cheaper normal membership. This includes the participation in all training sessions which are provided by us. You can purchase this as an adult person, it can be cancelled monthly, otherwise your membership will be automatically renewed.",
        "Our children's offer",
        "Also our children are favored compared to a normal membership, with 45€ every half year you get a cheaper normal membership. This includes the participation in all training sessions which are provided by us. You can purchase this as an adult person, it can be cancelled monthly, otherwise your membership will be automatically renewed.",
        "Short Term Membership",
        "As one of the few martial arts club / schools Kenkyo offers for the first time short-term memberships. For a one-time fee of 30€ you can come as often as you want to train within 3 months. After that, you will be automatically canceled and can not book another short-term membership. So if you are still interested, the above offers are open.",
        "months",
        "In addition to the costs mentioned below, there is also an administrative cost of 20€.",
    ],
    "ja": [
        "当社からお客様へのご提案",
        '"5つのメンバーシップ "をご紹介します。ご興味のある方は、ぜひ体験トレーニングや短期会員登録のご予約をお願いします。お問い合わせいただいた後、すべての詳細情報をお送りします」。',
        '通常会員 "であること。',
        "「半年ごとに65€で、私たちが提供するすべてのトレーニングセッションへの参加を含む通常の会員権を得ることができます。大人で購入すると、毎月解約でき、そうでない場合は自動更新される」。",
        "ファミリーオファー ",
        'ファミリーオファー "は、スポーツが好きなご家族を対象としています。自分だけでなく、子どもやパートナーも、より良い条件でトレーニングすることができます。これは大人として購入することができ、毎月解約することができ、そうでない場合は会員が自動的に更新されます。2人目以降は、最高額の会員が通常料金を支払う。',
        "特に児童・生徒・研修生向け ",
        "「半期ごとに55ユーロで、生徒、学生、研修生が通常の会員より安く利用できます。これには、当社が提供するすべてのトレーニングへの参加も含まれます。満年齢で購入できる、毎月解約できる、それ以外は自動更新される」。",
        "私たちの子どもたちの提案",
        "「また、子どもたちには、半年ごとに45ユーロを支払うことで、通常の会員より安く利用できる特典もあります。これには、当社が提供するすべてのトレーニングへの参加も含まれます。大人で購入すると、毎月解約でき、それ以外は自動更新されます。",
        '短期会員 "であること。',
        '数少ない武道クラブ／スクール "である建協が、初めて短期会員制を導入。1回30€で、3ヶ月間何度でもトレーニングができます。それ以降は自動的にキャンセルとなり、再度短期会員を予約することはできません。だから、もしあなたがまだ興味を持っているならば、上記のオファーはあなたに開かれたものです」。',
        "月 ",
        "後述の費用に加えて、事務手数料として20ユーロがかかります。"

    ],
    "un": [
        "Ajánlataink Önnek",
        "Az alábbi 5 tagságunk. Ha felkeltettük érdeklődését, szívesen látjuk, ha próbatanfolyamot szervez vagy rövid távú tagságot foglal. Minden további információt a kapcsolatfelvételt követően kap meg",
        "Normál tagság",
        "Félévente 65€-ért megkapod a normál tagságunkat, amely magában foglalja a részvételt az összes általunk biztosított edzésen. Ezt felnőttként is megvásárolhatod, havonta lemondható, egyébként a tagságod automatikusan megújul",
        "A családi ajánlat",
        "Családi ajánlatunk a sportot szerető családoknak szól. Nemcsak Ön, hanem gyermeke vagy partnere is jobb ajánlatot kaphat. Ezt felnőttként lehet megvásárolni, havonta lemondható, ellenkező esetben a tagság automatikusan megújul. A 2. tagtól kezdve a legmagasabb tag a normál díjat fizeti,",
        "Különösen a tanulók, hallgatók és gyakornokok számára",
        "Félévente 55€-val olcsóbb normál tagságot kapnak diákjaink, hallgatóink és gyakornokaink. Ez magában foglalja az általunk biztosított valamennyi képzésen való részvételt. Ezt nagykorú személyként lehet megvásárolni, havonta felmondható, ellenkező esetben a tagság automatikusan megújul",
        "Gyermekeink ajánlata",
        "Gyermekeinknek is különleges ajánlatot kínálunk a normál tagsághoz képest, félévente 45€-val olcsóbban kapnak normál tagságot. Ez magában foglalja az általunk biztosított valamennyi képzésen való részvételt. Ezt felnőttként is megvásárolhatod, havonta lemondható, egyébként a tagságod automatikusan megújul",
        "Rövid távú tagság",
        "A Kenkyo azon kevés harcművészeti klubok/iskolák egyikeként először kínál rövid távú tagságot. Egyszeri 30€-ért 3 hónapon belül annyiszor edzhetsz, ahányszor csak szeretnél. Ezt követően automatikusan törlésre kerül, és nem foglalhat újabb rövid távú tagságot. Tehát ha még mindig érdekel, a fenti ajánlatok nyitva állnak számodra.",
        "hónapok",
        "Az alább említett költségeken kívül 20 euró adminisztrációs költség is felmerül.",
    ],
    "uk": ["Наші пропозиції для вас",
        "Нижче наведено 5 наших членських організацій. Якщо ви зацікавлені, ви можете домовитися про пробне тренування або замовити короткострокове членство. Ви отримаєте всю додаткову інформацію після того, як зв'яжетеся з нами",
        "Звичайне членство",
        "За 65 євро кожні півроку ви отримуєте наше звичайне членство, яке включає в себе участь у всіх тренінгах, які ми проводимо. Ви можете придбати його як дорослий, його можна скасовувати щомісяця, інакше ваше членство буде автоматично поновлене",
        "Сімейна пропозиція",
        "Наша сімейна пропозиція орієнтована на сім'ї, які люблять спорт. Не тільки ви, а й ваша дитина або партнер може тренуватися за кращою пропозицією. Його можна придбати для повнолітніх, його можна скасовувати щомісяця, інакше ваше членство буде автоматично поновлене. Починаючи з 2-го учасника, найвищий учасник сплачує звичайну ставку,",
        "Особливо для учнів, студентів та стажерів",
        "За 55 євро кожні півроку наші учні, студенти та стажери отримують дешевший звичайний абонемент. Це включає в себе участь у всіх тренінгах, які ми проводимо. Ви можете придбати його як повнолітня особа, його можна скасовувати щомісяця, інакше ваше членство буде автоматично поновлене",
        "Пропозиція наших дітей",
        "Нашим дітям також пропонується спеціальний тариф у порівнянні зі звичайним абонементом: за 45 євро кожні півроку ви отримуєте дешевший звичайний абонемент. Це включає участь у всіх тренінгах, які ми проводимо. Ви можете придбати його як дорослий, його можна скасовувати щомісяця, інакше ваше членство буде автоматично поновлене",
        "Короткострокове членство",
        "Як один з небагатьох клубів/шкіл бойових мистецтв, Кенкьо вперше пропонує короткострокове членство. За одноразовий внесок у розмірі 30 євро ви можете тренуватися скільки завгодно протягом 3 місяців. Після цього ваше членство буде автоматично анульовано, і ви не зможете забронювати наступне короткострокове членство. Тож якщо ви все ще зацікавлені, вищезгадані пропозиції відкриті для вас",
        "Місяці",
        "На додаток до витрат, згаданих нижче, існує також адміністративний збір у розмірі 20 євро",
    ]
}
